### ISSUE TITLE
Login button color

### ISSUE THREAD

**Issue by CurtDarryl** [cathvidas/KEP_TMS_UI#2]
I think you should change the color of the Login button to a richer one. I think the current color is too pale.

![image](https://github.com/user-attachments/assets/488cbdb2-e908-491d-924f-37f975cfc803)

**Comment by cathvidas** [comment]
done changing the color
![image](https://github.com/user-attachments/assets/d39a68a4-b0a4-4305-8ed6-e5e327d60e99)
