### ISSUE TITLE
Login - Error Message Suggestion

### ISSUE THREAD

**Issue by cathvidas** [cathvidas/KEP_TMS_UI#4]
Please change the error message into more meaningful one, highlighting both the fields to be inputted by the user..
![image](https://github.com/user-attachments/assets/ecf95071-cd1a-437d-948f-4171845ddb7d)

**Comment by CurtDarryl** [comment]
added a warning message if both inputs are empty

![image](https://github.com/user-attachments/assets/c1c1e8e2-1c5c-436e-a175-51244091190a)
