### ISSUE TITLE
Security / Session / Data Filter Issue

### ISSUE THREAD

**Issue by cathvidas** [cathvidas/KEP_TMS_UI#5]
User can still navigate to pages even if he/she didn't login into the system. 
Additionally, user session were not properly cleared. Data can still be fetched making the system not highly reliable with  data privacy and security chuchu. (sakto ba haha)
![image](https://github.com/user-attachments/assets/77437e51-3c0c-4d2c-b795-6be979207be4)
![image](https://github.com/user-attachments/assets/6852505a-3966-4b8b-8453-656d2e355853)

**Comment by CurtDarryl** [comment]
I added a condition where the system would check if the user is logged in, and if not, the user will be redirected to Login Page
